/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package jdbc.java.udemy.app;

import db.DB;
import jdbc.java.udemy.list.LinkedList;

import static jdbc.java.udemy.utilities.StringUtils.join;
import static jdbc.java.udemy.utilities.StringUtils.split;
import static jdbc.java.udemy.app.MessageUtils.getMessage;

import org.apache.commons.text.WordUtils;

import java.sql.Connection;

public class App {
    public static void main(String[] args) {

        Connection conn = DB.getConnection();
        DB.closeConnection();
    }
}
